services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
    image: zoomarket-catalog-api:latest
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=catalog;Username=postgres;Password=password
    depends_on:
      - postgres
      - rabbitmq
      - redis

  user.api:
    build:
      context: .
      dockerfile: User/User.API/Dockerfile
    image: zoomarket-user-api:latest
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=user;Username=postgres;Password=password
    depends_on:
      - postgres

  order.api:
    build:
      context: .
      dockerfile: Order/Order.API/Dockerfile
    image: zoomarket-order-api:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080  
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=order;Username=postgres;Password=password
    depends_on:
      - postgres
      - rabbitmq

  review.api:
    build:
      context: .
      dockerfile: Review/Review.API/Dockerfile
    image: zoomarket-review-api:latest
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=review;Username=postgres;Password=password
    depends_on:
      - postgres
      - rabbitmq

  payment.api:
    build:
      context: .
      dockerfile: Payment/Payment.API/Dockerfile
    image: zoomarket-payment-api:latest
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=payment;Username=postgres;Password=password
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: